---
- name: Verify nfs-utils is installed
  ansible.builtin.yum:
    name: '{{ item }}'
    state: present
  loop: '{{ nfs_rpm_packages }}'

- name: Create NFS shared directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  loop: '{{ create_nfs_dirs }}'

- name: Configure nfs exports
  ansible.builtin.template:
    src: etc/exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
  notify: exportfs

- name: Prevent NFS mounting of any v3 or less
  ansible.builtin.systemd:
    name: '{{ item }}'
    state: stopped
    masked: true
  loop: '{{ disabled_nfs_services }}'

- name: Push /etc/sysconfig/nfs to server
  ansible.builtin.template:
    src: etc/sysconfig/nfs.j2
    dest: /etc/sysconfig/nfs
    owner: root
    group: root
    mode: '0644'

- name: Reload NFS
  ansible.builtin.systemd:
    name: nfs
    enabled: true
    state: reloaded

- name: Configure FirewallD
  ansible.posix.firewalld:
    service: nfs
    permanent: true
    state: enabled
  notify: restart firewalld
  tags: firewall
