---
#
# This playbook builds a base Redhat or CentOS system.
#
- name: Redhat/Centos Playbook
  hosts: all
  become: true
  gather_facts: true

# This is for the redhat_subscription input prompts:
  vars_prompt:
    - name: redhat_subscription_username
      prompt: "Enter the Redhat Subscription Username"

    - name: redhat_subscription_password
      prompt: "Enter the Redhat Subscription Password"

  roles:
    - redhat_centos_base
    - nagios
    - clamav
    - splunk
    - nfs_clients
    - systemd_mounts
