---
- hosts: all
  become: yes
  gather_facts: false
  tasks:

    - name: Kill yum and Remove /var/run/yum.pid
      shell: /usr/bin/pkill -9 -f yum && rm -f /var/run/yum.pid
      ignore_errors: true

    - name: Clean metadata
      command: yum clean all
      ignore_errors: true

    - name: Run updates
      yum:
        name: '*'
        download_only: true
        update_cache: yes
        state: latest
