---
- name: Pre-run Updates
  hosts: all
  become: true
  gather_facts: false
  tasks:

    - name: Kill yum and Remove yum.pid
      ansible.builtin.shell: /usr/bin/pkill -9 -f yum && rm -f /var/run/yum.pid
      failed_when: false
      changed_when: false

    - name: Clean Metadata
      ansible.builtin.command: yum clean all
      failed_when: false
      changed_when: false

    - name: Run Updates
      ansible.builtin.yum:
        name: '*'
        download_only: true
        update_cache: true
        state: latest
        update_only: true
