---
- name: Clean Rancher Nodes (Round 1)
  hosts: all
  become: true
  gather_facts: false
  roles:
    - { role: rancher, rancher_state: One }

- name: Clean Rancher Nodes (Round 2)
  hosts: all
  become: true
  gather_facts: false
  roles:
    - { role: rancher, rancher_state: Two }
