---
- name: Redhat Centos Base Playbook
  hosts: all
  become: true
  gather_facts: true

# This is for the redhat_subscription input prompts:
  vars_prompt:
    - name: redhat_subscription_username
      prompt: "Enter the Redhat Subscription Username"

    - name: redhat_subscription_password
      prompt: "Enter the Redhat Subscription Password"

  roles:
    - redhat_centos_base
