---
- name: Run Updates
  hosts: all
  become: true
  gather_facts: false
  tasks:

    - name: Stopping all Tomcats
      ansible.builtin.systemd:
        name: '{{ item }}'
        state: stopped
      loop: '{{ tomcat_services }}'
      failed_when: false
      changed_when: false
      tags: stop_tomcats

    - name: Stopping Core Services
      ansible.builtin.systemd:
        name: '{{ item }}'
        state: stopped
      loop: '{{ core_services }}'
      failed_when: false
      changed_when: false
      tags: stop_services

    - name: Stopping Postgresql
      ansible.builtin.systemd:
        name: postgresql-9.6
        state: stopped
      failed_when: false
      tags: stop_postgres

    - name: Kill yum and Remove yum.pid
      ansible.builtin.shell: /usr/bin/pkill -9 -f yum && rm -f /var/run/yum.pid
      failed_when: false
      changed_when: false

    - name: Run Updates
      ansible.builtin.yum:
        name: '*'
        update_cache: true
        state: latest
        update_only: true

    - name: Reboot server
      ansible.builtin.reboot:
      tags: reboot
