---
- name: Yum Clean
  command: yum clean metadata

- name: Restart sshd
  service:
    name: sshd
    enabled: true
    state: restarted

- name: Restart postfix
  service:
    name: postfix
    enabled: true
    state: restarted

- name: Restart auditd
  service:
    name: auditd
    enabled: true
    state: restarted

- name: Restart rsyslog
  service:
    name: rsyslog
    enabled: true
    state: restarted

- name: Update ca-trust
  command: /usr/bin/update-ca-trust

- name: Restorecon
  command: '/usr/sbin/restorecon -iv {{ item }}'
  loop: '{{ restorecon_files }}'

- name: Sebools
  command: '/usr/sbin/setsebool -P {{ item }} on'
  loop: '{{ sebools }}'
