---
- name: Yum Clean
  ansible.builtin.command: yum clean metadata

- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    enabled: true
    state: restarted

- name: Restart postfix
  ansible.builtin.service:
    name: postfix
    enabled: true
    state: restarted

- name: Restart auditd
  ansible.builtin.service:
    name: auditd
    enabled: true
    state: restarted

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    enabled: true
    state: restarted

- name: Update ca-trust
  ansible.builtin.command: /usr/bin/update-ca-trust

- name: Restorecon
  ansible.builtin.command: '/usr/sbin/restorecon -iv {{ item }}'
  loop: '{{ restorecon_files }}'

- name: Sebools
  ansible.builtin.command: '/usr/sbin/setsebool -P {{ item }} on'
  loop: '{{ sebools }}'
