---
- name: Verify nfs-utils is installed
  yum:
    name: nfs-utils
    state: present

- name: Stopping all tomcats
  systemd:
    name: '{{ item }}'
    state: stopped
  loop: '{{ tomcat_services }}'
  ignore_errors: true
  tags: stop_services

- name: Stopping core services
  systemd:
    name: '{{ item }}'
    state: stopped
  loop: '{{ core_services }}'
  ignore_errors: true
  tags: stop_services

- name: Stopping postgresql
  systemd:
    name: postgresql-9.6
    state: stopped
  ignore_errors: true
  tags: stop_services

- name: Disable Autofs
  systemd:
    name: autofs
    state: stopped
    enabled: no

- name: Remove /etc/auto.master
  file:
    path: /etc/auto.master
    state: absent
