---
- name: Verify Samba RPMs are installed
  ansible.builtin.yum:
    name: '{{ item }}'
    state: present
  loop: '{{ samba_rpm_packages }}'

- name: Push Samba config files
  ansible.builtin.template:
    owner: root
    group: root
    mode: '0644'
    src: etc/samba/smb.conf.j2
    dest: /etc/samba/smb.conf
  notify: start samba
