---
#
# Enable systemd mount units
#

- name: enable net-home.mount
  systemd:
    name: net-home.mount
    state: started
    enabled: yes
    daemon_reload: yes

- name: enable net-sechome.mount
  systemd:
    name: net-sechome.mount
    state: started
    enabled: yes
    daemon_reload: yes

- name: enable net-pg-staging_log.mount
  systemd:
    name: net-pg-staging_log.mount
    state: started
    enabled: yes
    daemon_reload: yes

- name: enable net-pg-staging_backup.mount
  systemd:
    name: net-pg-staging_backup.mount
    state: started
    enabled: yes
    daemon_reload: yes

- name: enable mnt-secure-webdocs.mount
  systemd:
    name: mnt-secure-webdocs.mount
    state: started
    enabled: yes
    daemon_reload: yes

- name: enable mnt-webapps.mount
  systemd:
    name: mnt-webapps.mount
    state: started
    enabled: yes
    daemon_reload: yes

- name: enable mnt-webdocs.mount
  systemd:
    name: mnt-webdocs.mount
    state: started
    enabled: yes
    daemon_reload: yes

- name: enable net-jenkins-home.mount
  systemd:
    name: net-jenkins-home.mount
    state: started
    enabled: yes
    daemon_reload: yes

- name: enable usr-local-webapps.mount
  systemd:
    name: usr-local-webapps.mount
    state: started
    enabled: yes
    daemon_reload: yes

- name: enable net-nagios-nagiosgraph.mount
  systemd:
    name: net-nagios-nagiosgraph.mount
    state: started
    enabled: yes
    daemon_reload: yes
